<Project Sdk="Aspire.AppHost.Sdk/13.4.6">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <UserSecretsId>68e5d917-faf5-4d84-8d60-753b91c9bdcb</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\src\ChurchWebsite.Api\ChurchWebsite.Api.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Aspire.Hosting.PostgreSQL" Version="13.4.6" />
      <PackageReference Include="Aspire.Hosting.JavaScript" Version="13.4.6" />
    </ItemGroup>

</Project>
