<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\..\ChurchWebsite.ServiceDefaults\ChurchWebsite.ServiceDefaults.csproj" />
    <ProjectReference Include="..\ChurchWebsite.Core\ChurchWebsite.Core.csproj" />
    <ProjectReference Include="..\ChurchWebsite.Infrastructure\ChurchWebsite.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FastEndpoints" Version="8.1.0" />
    <PackageReference Include="FastEndpoints.Security" Version="8.1.0" />
    <PackageReference Include="FastEndpoints.Swagger" Version="8.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.8" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>f622b0a1-3a18-4ef5-ad0f-5b9154eab437</UserSecretsId>
  </PropertyGroup>

</Project>
